//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMS.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnquiryDetail
    {
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string DOB { get; set; }
        public string Mobile { get; set; }
        public string Class { get; set; }
        public string Address { get; set; }
        public string Course { get; set; }
        public string Email { get; set; }
        public Nullable<System.DateTime> EntryTime { get; set; }
        public Nullable<System.DateTime> ResolvedTime { get; set; }
        public Nullable<System.DateTime> Dated { get; set; }
    }
}
